"""empty message

Revision ID: dc51794cded4
Revises: None
Create Date: 2016-09-06 00:26:35.082376

"""

# revision identifiers, used by Alembic.
revision = 'dc51794cded4'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('tz_offset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'phone'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tz_offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', 'phone', name='user_pkey'),
    sa.UniqueConstraint('name', name='user_name_key'),
    sa.UniqueConstraint('phone', name='user_phone_key')
    )
    op.drop_table('user_data')
    ### end Alembic commands ###
